"""order status enum

Revision ID: 963426a4bda0
Revises: 8b39070b9a6d
Create Date: 2026-07-24 11:38:26.864679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '963426a4bda0'
down_revision: Union[str, Sequence[str], None] = '8b39070b9a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('new', 'contacted', 'confirmed', 'cancelled', name='order_status', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('new', 'contacted', 'confirmed', 'cancelled', name='order_status', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
